### PR TITLE
verb / adj associated

### PR DESCRIPTION
**Pull request by varmichelle**

### CODE REVIEW

**Comment by varmichelle** [comment]
Running out of memory :(((((((((((

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at edu.stanford.nlp.parser.lexparser.LexicalizedParserQuery.parseAndReport(LexicalizedParserQuery.java:706)
	at edu.stanford.nlp.parser.lexparser.ParseFiles.parseFiles(ParseFiles.java:215)
	at edu.stanford.nlp.parser.lexparser.ParseFiles.parseFiles(ParseFiles.java:75)
	at edu.stanford.nlp.parser.lexparser.LexicalizedParser.main(LexicalizedParser.java:1518)

**Comment by varmichelle** [comment]
I'm also getting this error immediately after: (the same one @srisi encountered)
I suspect this is because of the out of memory error above
raise OSError('Java command failed : ' + str(cmd))
OSError: Java command failed : ['/usr/bin/java', '-mx1000m', '-cp', 'assets/stanford-parser-3.9.1-models.jar:assets/stanford-parser-3.9.1-models.jar:assets/stanford-parser.jar', 'edu.stanford.nlp.parser.lexparser.LexicalizedParser', '-model', 'edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz', '-sentences', 'newline', '-outputFormat', 'conll2007', '-encoding', 'utf8', '/var/folders/6x/pvsnhlgn7s33yzdq6b859rhc0000gn/T/tmpp0n5mgxv']

**Comment by asselism** [comment]
In #239 added the other types of verbs because VBD only catches verbs in past tense.

**Comment by srisi** [comment]
At this point we're so close to finishing this project (not just the code deadline but the writeup deadline) that you just need to use some ugly solutions. How about skipping the novels that produce memory errors?
```
        try:
            row = parse_novel(novel, parser)
        except OSError:
            continue
```

**Comment by varmichelle** [comment]
> At this point we're so close to finishing this project (not just the code deadline but the writeup deadline) that you just need to use some ugly solutions. How about skipping the novels that produce memory errors?
> 
> ```
>         try:
>             row = parse_novel(novel, parser)
>         except OSError:
>             continue
> ```
> PS: make to sure to resolve the conflicts with the merged #239. Thanks.

Hm, I think the memory issue is caused by loading too many large files into memory at once. I don't think certain novels are causing this; the problem will occur if we try doing more than one novel at once.

**Comment by varmichelle** [comment]
Okay memory issues should be fixed now! Thanks @srisi

**Pull request merged**
