### PR TITLE
Created 'get_metadata_fields' and 'get_field_vals' methods of Corpus

### PR DESCRIPTION
**Pull request by cminsky**
`get_metadata_fields` allows the user to get a list of all the metadata fields in a corpus.

`get_field_vals` allows the user to get a list of all the values of a particular metadata field in a corpus.

These will be important for the subcorpus method.

`get_field_vals` could probably use more tests.

### CODE REVIEW

**Comment by cminsky** [comment]
I just noticed that `get_metadata_fields` conflicts with pull request #176. It is still worth having `get_data_fields` but I'll have to rework it to be compatible.

**Comment by equationcrunchor** [comment]
Sorry! Next time I’ll post what I’m doing to #general

**Comment by equationcrunchor** [comment]
Erm, why can't I see your changes on GitHub?  Did you commit and push to origin?

**Comment by equationcrunchor** [comment]
Should I continue working on get_field_vals or stop?

**Comment by mscuthbert** [comment]
I see no changed files.  Can this PR be closed?  Thanks!

**Comment by cminsky** [comment]
Yep. I'll create a new one w/ overlap resolved later.

**Pull request closed without merging**
