### PR TITLE
Adding book to corpus

### PR DESCRIPTION
**Pull request by ifeife123**
Books where collected from Project Gutenberg. The meta data was added to the google drive spreadsheet. 11 books taken instead of 9 as complete metadata for two books was not available.

### CODE REVIEW

**Comment by elenaboal** [comment]
Please clarify why are there 11 instead of 9 if 2 books were missing?

**Comment by ifeife123** [comment]
The 2 books where not missing, they were missing metadata. Specifically, the country of origin. I uploaded them anyway but as a safety in case they were not able to be used I uploaded two extras.

Sent from Mail for Windows 10

**Comment by srisi** [comment]
In that case, can you slack me the metadata for those two novels so I can add them?
Thanks.

**Comment by ifeife123** [comment]
I already added the data to the google doc spreadsheet. 

Sent from Mail for Windows 10

**Pull request merged**
