### PR TITLE
Added ten book .txt files from Project Gutenberg

### PR DESCRIPTION
**Pull request by ArrowAce**
These ten books for authors with last names I, J, W are all within our project's years of study and all in the public domain in the United States. They were all manually downloaded from Project Gutenberg.

### CODE REVIEW

**Comment by srisi** [comment]
Thank you!
@ltagliaferri @mscuthbert : Thoughts on including short story collections (Dubliners)? I think it's fine, gender-representation wise, in particular with the initial dataset, plus there will probably be others that sneak in but are less famous and therefore harder to identify.

**Comment by ltagliaferri** [comment]
I advised the group to stick with novels and to cross-check with something like Wikipedia to ensure that they were looking at novels. My concern would be to be sure to include a robust sampling of short story collections. We can ask the Data team for their thoughts.

**Comment by ArrowAce** [comment]
I replaced Joyce's "Dubliners" with "Ulysses," which is a novel proper. If we re-examine the short stories question at a future date and decide we are fine with including them, we can always bring back "Dubliners" then.

**Comment by mscuthbert** [comment]
The Dead is almost long enough to consider a novella but I agree that Ulysses is better to have. Sort of a culmination of the last major work to be out of copyright.

**Comment by srisi** [comment]
Thanks for the copy right write-up as well!

**Pull request merged**
